### ISSUE TITLE
kernel_require.rb --> `require': cannot load such file

### ISSUE THREAD

**Issue by jorgeceballosgarcia** [PopulateTools/ansible-doc-generator#22]
Hello!!

I have this problem on MacOS Ventura Apple Silicon Chip

`
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in require: cannot load such file -- pry (LoadError)
Did you mean?  pty
        from <internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in require
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/ansible_doc_generator-0.1.0/lib/ansible_doc_generator.rb:2:in <top (required)>
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/ansible_doc_generator-0.1.0/bin/ansible-doc-generator:5:in require_relative
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/ansible_doc_generator-0.1.0/bin/ansible-doc-generator:5:in <top (required)>
        from /opt/homebrew/lib/ruby/gems/3.2.0/bin/ansible-doc-generator:25:in load
        from /opt/homebrew/lib/ruby/gems/3.2.0/bin/ansible-doc-generator:25:in <main>
`

Versions:

`
ruby --version
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]
gem --version
3.4.9
`

**Comment by eltercero** [comment]
Hi there,

There is a bug related to that dependency (it shouldn't be required). Until we fix it, and as a workaround, you can install the dependency manually with:

`gem install pry`

After that it should work.
